# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

epollImpl <- function() {
    .Call('_epollPromise_epollImpl', PACKAGE = 'epollPromise')
}

#' @export
close_socket <- function(fileno) {
    invisible(.Call('_epollPromise_close_socket', PACKAGE = 'epollPromise', fileno))
}

socket_create <- function(addr, port) {
    .Call('_epollPromise_socket_create', PACKAGE = 'epollPromise', addr, port)
}

#' @export
readLine <- function(fileno) {
    .Call('_epollPromise_readLine', PACKAGE = 'epollPromise', fileno)
}

#' @export
writeLine <- function(fileno, str) {
    invisible(.Call('_epollPromise_writeLine', PACKAGE = 'epollPromise', fileno, str))
}

epoll_wait <- function(epollfd) {
    .Call('_epollPromise_epoll_wait', PACKAGE = 'epollPromise', epollfd)
}

subscribe <- function(epollfd, fileno, unsubscribe) {
    invisible(.Call('_epollPromise_subscribe', PACKAGE = 'epollPromise', epollfd, fileno, unsubscribe))
}

